baseURL = 'https://nicode.it/'
languageCode = 'en-us'
title = 'nicode.it'
theme = 'archie'

[Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true
